### PR TITLE
Revise requirements

### PR DESCRIPTION
**Pull request by heidiaclayton**
This is going to have my revisions to the design, tech review, and requirements docs. The requirements doc needed only a very small change.

### CODE REVIEW

**Comment by lewismc** [comment]
+1

**Comment by heidiaclayton** [comment]
@browtayl I have revised all of my sections of the course documents for the final submission. Are you okay with merging?

**Comment by ghost** [comment]
@heidiaclayton It's your docs, no need to ask me :-) As long as the PDFs build I'm sure it's fine. We can do a more thorough proofread and edit starting Friday.

You might consider doing a dreaded squash with `git rebase -i` considering that all the commit messages are basically the same, but w/e.

**Comment by heidiaclayton** [comment]
Ok, confirmed that it builds with the makefile.

**Pull request merged**
