### PR TITLE
Issue 19 mining classification

### PR DESCRIPTION
**Pull request by ghost**
This pull request implements a working mining classifier per issue https://github.com/capstone-coal/pycoal/issues/19 and comments out broken code in anticipation of milestone [0.2](https://github.com/capstone-coal/pycoal/milestone/1).

### CODE REVIEW

**Comment by ghost** [comment]
I have used the mining classifier to analyze some of our new imagery. First I downloaded all the LC images from the server onto my local machine:
```
$ sftp -i foo.pem ec2-user@bar:AVNG_data_distribution
Connected to bar.
Changing to: /home/ec2-user/AVNG_data_distribution
sftp> get -R LC
```
I rotated the Craig image with my custom build of gdalwarp:
```
$ cd LC/
$ cd ang20140912t192359_rfl_v1c
$ export PATH=/media/study/OSU/winter17/cs462/gdal/gdal/gdal/apps:$PATH
$ gdalwarp -of envi ang20140912t192359_corr_v1c_img_class.img ang20140912t192359_corr_v1c_img_class_rot.img
```
Then I manually edited the header to restore deleted fields. This won't be a problem with a QGIS built against GDAL 2.2.0+.

Finally I used the mining classifier which removes all the classes from the image except the ones we are interested in. I left it up to the user to supply the classes as a parameter, giving the method more flexibility:
```
$ python
>>> import sys
>>> sys.path.append('/media/study/OSU/spring17/cs463/coal/')
>>> import pycoal
>>> import pycoal.mining
>>> mc = pycoal.mining.MiningClassification([u'Schwertmannite BZ93-1 s06av95a=b', u'Renyolds_TnlSldgWet SM93-15w s06av95a=a', u'Renyolds_Tnl_Sludge SM93-15 s06av95a=a'])
>>> mc.classifyImage('ang20140912t192359_corr_v1c_img_class_rot.hdr','ang20140912t192359_corr_v1c_img_class_rot_mining.hdr')
Saving /media/study/OSU/fall16/cs461/data/AVNG_data_distribution/LC/ang20140912t192359_rfl_v1c/ang20140912t192359_corr_v1c_img_class_rot_mining.img
```
I have posted screenshots of the [mineral](https://drive.google.com/open?id=0BxysdOuBmaIGVUVGTnFQekRfY3c) and [mining](https://drive.google.com/open?id=0BxysdOuBmaIGQTNjYjV0a3k2Q3c) classified images to our Google Drive.

**Comment by ghost** [comment]
I removed the GDAL dependency because it causes a build failure and is not currently necessary.

**Comment by ghost** [comment]
The remaining build failure appears to be due to pylint.

**Comment by ghost** [comment]
I also classified the three new San Juan images:
```
>>> mc.classifyImage('/media/study/OSU/spring17/cs463/data/AVNG_data_distribution/LC/ang20150420t180624_rfl_v1e/ang20150420t180624_corr_v1e_img_class.hdr', '/media/study/OSU/spring17/cs463/data/AVNG_data_distribution/LC/ang20150420t180624_rfl_v1e/ang20150420t180624_corr_v1e_img_class_mining.hdr')
Saving /media/study/OSU/fall16/cs461/data/AVNG_data_distribution/LC/ang20150420t180624_rfl_v1e/ang20150420t180624_corr_v1e_img_class_mining.img
>>> mc.classifyImage('/media/study/OSU/spring17/cs463/data/AVNG_data_distribution/LC/ang20150420t184333_rfl_v1e/ang20150420t184333_corr_v1e_img_class.hdr', '/media/study/OSU/spring17/cs463/data/AVNG_data_distribution/LC/ang20150420t184333_rfl_v1e/ang20150420t184333_corr_v1e_img_class_mining.hdr')
Saving /media/study/OSU/fall16/cs461/data/AVNG_data_distribution/LC/ang20150420t184333_rfl_v1e/ang20150420t184333_corr_v1e_img_class_mining.img
>>> mc.classifyImage('/media/study/OSU/spring17/cs463/data/AVNG_data_distribution/LC/ang20150420t185951_rfl_v1e/ang20150420t185951_corr_v1e_img_class.hdr', '/media/study/OSU/spring17/cs463/data/AVNG_data_distribution/LC/ang20150420t185951_rfl_v1e/ang20150420t185951_corr_v1e_img_class_mining.hdr')
Saving /media/study/OSU/fall16/cs461/data/AVNG_data_distribution/LC/ang20150420t185951_rfl_v1e/ang20150420t185951_corr_v1e_img_class_mining.img
```
Each of these I likewise manually rotated and edited the header. When I loaded them into QGIS, the first image was empty and the second two contained overlapping patterns. A [screenshot](https://drive.google.com/open?id=0BxysdOuBmaIGYUxBQjhHZ1VRM00) of this is also on Google Drive. Obviously our picture will be more complete when the rest of the images come in.

**Review by lewismc — APPROVED** [review]
+1 please merge into master branch. We can sort out linting later... are you working on it now?

**Comment by ghost** [comment]
@lewismc merged. we might want to disable pylint so that the 0.2 release will build and add the fixes to a later milestone.

**Pull request merged**
