### PR TITLE
ISSUE-212 Cleaned up SAM: includes the 3 implementations of SAM [Supersedes pull request #198]

### PR DESCRIPTION
**Pull request by Luner**
Essentially the three algorithms shared a lot of code which made it challenging to scroll through and understand what was happening.  This took what was repeated out into its own SAM algorithm that calls upon the different methods to populate the scored and classified arrays. 

I found that having each of the methods listed in this manner makes it easier to compare each of the different implementations as well as potentially modify/add additional methods more easily.

This issue also adds a progress bar using tqdm which can be helpful for runtime comparisons as well as progress monitoring.

Note: This pull request would replace #198

### CODE REVIEW

**Comment by Luner** [comment]
I already tested the pytorch implementation and got the same results as before and plan on running one of the others overnight.

**Comment by lewismc** [comment]
This is brilliant @Luner excellent work... really.

**Comment by lewismc** [comment]
Once this is merged into master, we will be good to close off the current USC project.

**Comment by Luner** [comment]
@lewismc I fixed most of the deepsource issues:
The issue it lables as major is a trick within pytorch to set all of the nan values to 0.
The rest involve the function names and I was not sure if we wanted to change these

Other than that this branch should be ready to go.

**Comment by lewismc** [comment]
Excellent work @Luner seriously. Excellent job.

**Pull request merged**
