### PR TITLE
test mining classification

### PR DESCRIPTION
**Pull request by ghost**
this pull implements testing for mining classification per issue https://github.com/capstone-coal/pycoal/issues/57.

the test runs the mining classifier on a 10x10 mineral-classified subimage and compares the result elementwise with a known-good 10x10 mining-classified subimage. temporary files are generated in the test directory and then deleted.

### CODE REVIEW

**Comment by ghost** [comment]
@heidiaclayton Here is how I generated suitable subimages to test mining classification, using `spectral.imshow` to help find candidate regions:
```
>>> image = spectral.open_image('/media/study/OSU/spring17/cs463/data/AVNG_data_distribution/LC/ang20150420t182808_rfl_v1e/ang20150420t182808_corr_v1e_img_class.hdr')
>>> mining = spectral.open_image('/media/study/OSU/spring17/cs463/data/AVNG_data_distribution/LC/ang20150420t182808_rfl_v1e/ang20150420t182808_corr_v1e_img_class_mining.hdr')
>>> image
	Data Source:   '/media/study/OSU/spring17/cs463/data/AVNG_data_distribution/LC/ang20150420t182808_rfl_v1e/ang20150420t182808_corr_v1e_img_class.img'
	# Rows:          14113
	# Samples:         807
	# Bands:             1
	Interleave:        BIP
	Quantization:  16 bits
	Data format:    uint16
>>> mining
	Data Source:   '/media/study/OSU/spring17/cs463/data/AVNG_data_distribution/LC/ang20150420t182808_rfl_v1e/ang20150420t182808_corr_v1e_img_class_mining.img'
	# Rows:          14113
	# Samples:         807
	# Bands:             1
	Interleave:        BIP
	Quantization:  16 bits
	Data format:    uint16
>>> spectral.imshow(mining)
>>> spectral.envi.save_image('/media/study/OSU/spring17/cs463/coal/pycoal/tests/ang20150420t182808_corr_v1e_img_class_4200-4210_70-80.hdr', image[4200:4210,70:80,:], metadata=image.metadata)
Saving /media/study/OSU/fall16/cs461/coal/pycoal/tests/ang20150420t182808_corr_v1e_img_class_4200-4210_70-80.img
>>> spectral.envi.save_image('/media/study/OSU/spring17/cs463/coal/pycoal/tests/ang20150420t182808_corr_v1e_img_class_mining_4200-4210_70-80.hdr', mining[4200:4210,70:80,:], metadata=mining.metadata)
Saving /media/study/OSU/fall16/cs461/coal/pycoal/tests/ang20150420t182808_corr_v1e_img_class_mining_4200-4210_70-80.img
>>> foo = spectral.open_image('/media/study/OSU/spring17/cs463/coal/pycoal/tests/ang20150420t182808_corr_v1e_img_class_4200-4210_70-80.hdr')
>>> bar = spectral.open_image('/media/study/OSU/spring17/cs463/coal/pycoal/tests/ang20150420t182808_corr_v1e_img_class_mining_4200-4210_70-80.hdr')
>>> foo
	Data Source:   '/media/study/OSU/spring17/cs463/coal/pycoal/tests/ang20150420t182808_corr_v1e_img_class_4200-4210_70-80.img'
	# Rows:             10
	# Samples:          10
	# Bands:             1
	Interleave:        BIP
	Quantization:  16 bits
	Data format:    uint16
>>> bar
	Data Source:   '/media/study/OSU/spring17/cs463/coal/pycoal/tests/ang20150420t182808_corr_v1e_img_class_mining_4200-4210_70-80.img'
	# Rows:             10
	# Samples:          10
	# Bands:             1
	Interleave:        BIP
	Quantization:  16 bits
	Data format:    uint16
>>> foo.asarray().flatten()
memmap([  28,   28,  717,  230,  230,  940,  421, 1154, 1154,  742,   28,
         28,   79,  230,  230,  940,   61,   61,  742,  742,   28,   28,
        717,  230,  230,  230,  230,   61,  742,  742,   28,   28,  717,
        230,  230, 1021,  230,  940,   61,  421,   28,   28,  988,  230,
        230, 1021,  230,  940,   61,  742,   28,   28,  988,   79, 1021,
       1021, 1002,  742,  742,  742,   28,   28,   28,   79, 1021, 1021,
       1002, 1002,  230,  742,   28,   28,   28,   79, 1021, 1021, 1021,
       1002,  230,  742,   28,   28,   28,   79, 1021, 1021, 1021,  230,
       1002,  742,   28,   28,   28,   28,  406, 1021, 1021,  230, 1002,
       1002], dtype=uint16)
>>> bar.asarray().flatten()
memmap([0, 0, 0, 0, 0, 0, 0, 3, 3, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0], dtype=uint16)
>>> import sys
>>> sys.path.append('/media/study/OSU/spring17/cs463/coal/')
>>> import pycoal
>>> import pycoal.mining
>>> mc = pycoal.mining.MiningClassification([u'Schwertmannite BZ93-1 s06av95a=b', u'Renyolds_TnlSldgWet SM93-15w s06av95a=a', u'Renyolds_Tnl_Sludge SM93-15 s06av95a=a'])
>>> mc.classifyImage('/media/study/OSU/spring17/cs463/coal/pycoal/tests/ang20150420t182808_corr_v1e_img_class_4200-4210_70-80.hdr', '/media/study/OSU/spring17/cs463/coal/pycoal/tests/ang20150420t182808_corr_v1e_img_class_mining_4200-4210_70-80_test.hdr')
Saving /media/study/OSU/fall16/cs461/coal/pycoal/tests/ang20150420t182808_corr_v1e_img_class_mining_4200-4210_70-80_test.img
>>> baz = spectral.open_image('/media/study/OSU/spring17/cs463/coal/pycoal/tests/ang20150420t182808_corr_v1e_img_class_mining_4200-4210_70-80_test.hdr')
>>> baz.asarray().flatten()
memmap([0, 0, 0, 0, 0, 0, 0, 3, 3, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0], dtype=uint16)
>>> numpy.array_equal(bar.asarray(), baz.asarray())
True
```
Your steps will be similar to [test mineral classification](https://github.com/capstone-coal/pycoal/issues/36), except the files and number of classes are larger.

Here is how I ran the tests in my local environment from the testing directory:
```
$ export PYTHONPATH=/media/study/OSU/spring17/cs463/coal:$PYTHONPATH
$ nosetests
..
----------------------------------------------------------------------
Ran 2 tests in 0.058s

OK
```

**Comment by ghost** [comment]
The test failed on GitHub so I have to find a way to set the location correctly.

**Comment by ghost** [comment]
I found that test files should be named relative to the project directory, e.g., `pycoal/tests/ang*.hdr`.

**Comment by ghost** [comment]
The tests fail for Python 3 because I used `xrange` in the classifiers. If we are supporting Python 3, then we will have to replace it with `range`. I recommend we address that in a separate issue.

**Comment by lewismc** [comment]
ack, please commit and we can add

**Pull request merged**
