### PR TITLE
Fixed Problems with examples

### PR DESCRIPTION
**Pull request by bdegley4789**
I fixed the problems I could find with the example scripts. I also updated the README to show the changes I needed to fix in Anaconda3 which had been discover in this issue https://github.com/spectralpython/spectral/issues/67

### CODE REVIEW

**Comment by bdegley4789** [comment]
I'm not sure why ci/dockercloud and continuous-integration/travis-ci/pr failed my changes to the README.rst these aren't essential changes and can be removed if needed

**Review by lewismc — CHANGES_REQUESTED** [review]
@bdegley4789 thanks for working on this. Unfortunately, we cannot duplicate the following files ```environment.py```, ```mineral.py``` and ```mining.py```. They should be imported from the locally installed package. Please remove the duplicated code.

**Comment by lewismc** [comment]
@bdegley4789 the jobs fail as follows
```
EnviException: Image file /home/travis/build/capstone-coal/pycoal/pycoal/tests/images/ang20140912t192359_corr_v1c_img_400-410_10-20_rgb_test.img already exists. Use `force` keyword to force overwrite.
```
This is because you have made an attempt to check in the intermediate test files... these should not be checked in. Can you please update the .gitignore to make sure that these are never added to source code management?

**Comment by bdegley4789** [comment]
Ok I fixed all the errors with importing local files, so there are no duplicates. I also updated the gitignore and removed the test images. I'm not sure why Docker Cloud doesn't like my changes it gives me a 404 page not found when I click details and log in

**Review by lewismc — APPROVED** [review]

**Comment by lewismc** [comment]
This looks much better @bdegley4789 please merge into master branch

**Pull request merged**
