### PR TITLE
Issue 161

### LINKED ISSUE #161: Address DeepSource issues
There are a number of issues flagged by DeepSource as can be seen at https://deepsource.io/gh/capstone-coal/pycoal/issues/

This issue should resolve these issues.

### PR DESCRIPTION
**Pull request by theoilie**
Closes #161. I'll wait for DeepSource to run and verify that the critical and major issues are resolved. After that, I can work on the minor/stylistic issues and then merge this.

This should resolve all instances of the following previously-present critical/major issues:

* File opened without the with statement (PTC-W0010)
* Dangerous default argument (PYL-W0102)
* Consider using enumerate for iteration (PYL-C0200)
* Invalid escape sequence found (FLK-W605)
* Module imported but unused (PYL-W0611)*
* No use of self (PYL-R0201)
* Unused variable found (PYL-W0612)
* Function contains unused argument (PYL-W0613)
* Anomalous backslash detected (PYL-W1401)
* Consider using in (PYL-R1714)

\* One caveat to note: The setup_module and teardown_module functions are flagged as unused imports but are actually used by nosetest. DeepSource will continue to think they're problematic, but the nosetest framework actually looks for those methods even though they're not directly called from within the individual tests.

### CODE REVIEW

**Comment by lewismc** [comment]
Good start, looking forward to the build stabilizing with the remaining checks if possible... otherwise we deactivate them e.g. for nosetests, etc.

**Comment by theoilie** [comment]
I was able to work around the nosetest caveat by explicitly redefining setup_module and teardown_module in each test file. I also addressed most of the minor things that DeepSource flagged that seem most problematic to me. Please also note that it looks like I added a lot of minor issues, but I think they were pre-existing things that weren't detected before - for example, naming variables M or N (for matrix dimensions) or h, m, s (for logging time).

At this point the problems are with naming and with calling gdal_proximity or gdal_rasterize (if a user has a malicious executable on their path with that same name, then that's a security risk - but I think that's extremely unlikely to happen). @lewismc Should we decide to leave those minor problems and merge? Also, I'm missing one major problem but I won't be able to tell which one it is until we merge so that DeepSource can re-analyze the master branch.

**Comment by sanketsaurav** [comment]
Hey @Lactem,

Regarding this:
> DeepSource will continue to think they're problematic, but the nosetest framework actually looks for those methods even though they're not directly called from within the individual tests.

You can silence any intentional issues raised easily via the source-code: https://deepsource.io/docs/configuration/skip-cq.html

Just noticed this, and I thought I'd drop by and let you know about this. Hope this helps! :)

Best,
Sanket
Founder, DeepSource

**Comment by theoilie** [comment]
> Hey @Lactem,
> 
> Regarding this:
> 
> > DeepSource will continue to think they're problematic, but the nosetest framework actually looks for those methods even though they're not directly called from within the individual tests.
> 
> You can silence any intentional issues raised easily via the source-code: https://deepsource.io/docs/configuration/skip-cq.html
> 
> Just noticed this, and I thought I'd drop by and let you know about this. Hope this helps! :)
> 
> Best,
> Sanket
> Founder, DeepSource

Thank you for letting me know! :)

**Comment by lewismc** [comment]
Excellent work @Lactem

**Pull request merged**
