### PR TITLE
ISSUE-111 Create examples directory with example scripts

### PR DESCRIPTION
**Pull request by lewismc**
This PR addresses #111 it is a first pass, so please wait if you intend to review and I will add more content taken directly from @browtayl 's examples at https://capstone-coal.github.io/docs#usage

### CODE REVIEW

**Comment by lewismc** [comment]
@heidiaclayton @browtayl can you guys please fetch this pull request and attempt to run unit tests... right now the environmental test is skipped as GDAL is not installed on the travis-ci server. 
If you have time, please also scope out to the examples portion of this PR, I hope that it lowers the barrier to folks generating some useful output from the toolkit. I still have not been able to source the USGS National Hydrography Dataset used in Environmenal Correlation... so hopefully once we can obtain this and provide a download link to it, we will have an end-to-end example for toolkit usage.
Also note, this PR addresses #46

**Comment by ghost** [comment]
Hey @lewismc , sorry about the delay. My "summer break" of a single week didn't leave a lot of time for taking care of the backlog. I skimmed this pull and didn't see anything amiss, but there was a lot of stuff to look through here. It might be slightly easier to review future pulls if the functional changes were separated into smaller chunks. Let me know if there are any specific things to look at, but I assume it works fine.

**Comment by lewismc** [comment]
ack, admittedly there was a lot and I didn't intend for it to be that way to be honest. Thanks for checking it out. I have a few improvements on the examples already e.g. process directory of data products as oppose to individual data products, I'll submit these in separate PR's after I implement the REST API.

**Comment by ghost** [comment]
Well I've been known to create [huge pull requests](https://github.com/capstone-coal/pycoal/pull/73/) so I can't talk. I'll have more feedback once I review the code in full rather than the diff.

**Pull request merged**
