### PR TITLE
ISSUE-20 environmental correlation

### PR DESCRIPTION
**Pull request by ghost**
work-in-progress pull request for [environmental correlation](https://github.com/capstone-coal/coal/issues/20)

### CODE REVIEW

**Comment by lewismc** [comment]
@browtayl can you please update the PR to suit the new directory layout. Sorry for the inconvenience. Thank you.

**Comment by ghost** [comment]
@lewismc no problem.

**Comment by ghost** [comment]
directory conflicts fixed.

**Comment by ghost** [comment]
closing this as it is being addressed per pull https://github.com/capstone-coal/pycoal/pull/33

**Pull request closed without merging**
