### PR TITLE
ISSUE-122 make SAM implementation available as a callback function

### PR DESCRIPTION
**Pull request by EvandroCT**
I came up with a simple manner to input varying args to varying classifiers algorithms. Already implemented and tested for SAM. This callback schema can be easily ported to other classifiers just by following the same function prototype already used with SAM's callback function.

### CODE REVIEW

**Comment by lewismc** [comment]
Hi @EvandroCT this looks good, however it has broken the unit tests and the examples also need to be updated.

**Comment by EvandroCT** [comment]
Hi @lewismc, I had to disable lines related to Sphinx in order to comply with Job 2 of the Travis build. Sphinx doesn't support python 3.3 such that there's no other way out to pass through all tests. Also, examples doesn't need to be changed yet because the performed changes do not affect the default interface of Mineral API. When we make other classifiers' callbacks available we could make specific documentation and examples for each one; DNN classifier included.

**Comment by EvandroCT** [comment]
@lewismc Damn, I just have merged by accident... sorry! Should I roll it back?

**Comment by EvandroCT** [comment]
PR moved to https://github.com/capstone-coal/pycoal/pull/155

**Pull request merged**
