### PR TITLE
Issue 59 add rgb

### PR DESCRIPTION
**Pull request by ghost**
this pull implements a `toRGB` method per issue https://github.com/capstone-coal/pycoal/issues/59.

this convenience method generates a three-band image for arbitrary wavelengths, by default red, green, and blue. this will allow us to easily load visible-light or other representations into QGIS to ease interpretation. as you can see in this [screenshot](https://drive.google.com/open?id=0BxysdOuBmaIGdnI3TnRzdUw5Nm8), QGIS displays the correct colors and metadata.

the method is static because it doesn't depend on the spectral library or any instance variables.

a unit test is included which converts a 1x1x432 source image and compares it with a known-good 1x1x3 rgb image.

### CODE REVIEW

**Comment by ghost** [comment]
@heidiaclayton here's how i generated the subimage for testing:
```
>>> sjFilename = '/media/study/OSU/spring17/cs463/data/AVNG_2015_data_distribution/L2/ang20150422t163638_rfl_v1e/ang20150422t163638_corr_v1e_img.hdr'
>>> sj = spectral.open_image(sjFilename)
>>> spectral.envi.save_image('/media/study/OSU/spring17/cs463/coal/pycoal/tests/ang20150422t163638_corr_v1e_img_987_654.hdr', sj[987,654,:], metadata=sj.metadata)
Saving /media/study/OSU/fall16/cs461/coal/pycoal/tests/ang20150422t163638_corr_v1e_img_987_654.img
```

**Comment by ghost** [comment]
the test fails in python 3 and i don't know why. yet another reason to resent whoever's idea it was to fork incompatible versions of the language.

**Comment by ghost** [comment]
okay, it was because `map` returns a list in python 2 but returns an iterator in python 3 which was getting exhausted. i fixed the method and the test passes now. it already proved its worth in catching a potentially ugly incompatibility.

**Comment by ghost** [comment]
i added a few conditionals and another test to support [this AVIRIS-C image](https://drive.google.com/open?id=0BxysdOuBmaIGbWJSd2FKRUhGTDA) from west virginia. i also ran the mining classifier, but recall that that image did not contain any coal classifications.

**Review by lewismc — APPROVED** [review]
Hi @browtayl this is grand. It's made me realize that we need to augment the release notes as the ```pycoal.version``` constant needs to be incremented with ever new development drive.

One other comment, are the relative paths read consistently across OS'?

**Comment by ghost** [comment]
@lewismc the [release page](https://github.com/capstone-coal/pycoal/wiki/Release#update-setuppy-and-docs-confpy) on the wiki talks about incrementing the version number in [`setup.py`](https://github.com/capstone-coal/pycoal/blob/master/setup.py#L42) and [`docs/source/conf.py`](https://github.com/capstone-coal/pycoal/blob/master/docs/source/conf.py#L71-L74). the code reads the version number from [`pycoal/__init__.py`](https://github.com/capstone-coal/pycoal/blob/master/pycoal/__init__.py). it would be nice if these weren't all in separate places, but i couldn't figure out how to do it.

the paths for the test files were specified relative to the project root for building with travis. they work on github and on my personal machine and presumably any unix system. i assume the tests won't work unmodified on windows because of the slashes. i haven't done any development on that platform so i don't really know. windows support could be investigated in another issue.

**Pull request merged**
