### PR TITLE
ISSUE-31 clean up docs directory

### PR DESCRIPTION
**Pull request by ghost**
this pull request reverts 4fe87a2d and fixes issue https://github.com/capstone-coal/pycoal/issues/31 to clean up the docs directory so that it will build on university servers. i moved the documents and includes into separate subdirectories and modified the makefile with a build script to source them directly. i also deleted obsolete pseudocode and updated the gitignore for convenience.

### CODE REVIEW

**Comment by ghost** [comment]
there is a preexisting **bug:** the DejaVu Sans Mono font is not available on the university servers, so the slideshow gets built with Computer Modern. the document is perfectly readable, so i don't think this is very important to fix. if i recall, the `.sty` file helps it build on systems (like mine) where the font is available but not known to TeX.

**Comment by ghost** [comment]
i did not delete the images that @heidiaclayton mentioned because at least one is still referenced by the one of the old documents.

**Comment by ghost** [comment]
@lewismc request review and approval to merge

**Review by lewismc — APPROVED** [review]
+1 merge

**Pull request merged**
