### PR TITLE
vizualize splib06

### PR DESCRIPTION
**Pull request by ghost**
This pull implements the splib visualization from issue https://github.com/capstone-coal/pycoal/issues/121 . Not a very sophisticated script. Requires Python 2.

Noticed that the other files might need `+x` permissions.

### CODE REVIEW

**Comment by ghost** [comment]
I added another script to generate a spectra graph for my poster. Neither script is documented currently.

**Comment by lewismc** [comment]
Hi @browtayl is this PR complete? I've run it locally and I think it looks great.

**Comment by ghost** [comment]
@lewismc If it's good enough for you, then it's good enough for me. I wasn't sure how you wanted these scripts documented or formatted so I didn't put anything into the README. That could always be addressed later.

**Comment by lewismc** [comment]
ACK, +1 please merge into master. These examples are great.

**Comment by lewismc** [comment]
ACK, +1 please merge into master. These examples are great.

**Comment by ghost** [comment]
merged and closed.

**Pull request merged**
